<a href="https://colab.research.google.com/github/umertabraiz/multivariate-linear-regression-practice/blob/main/Multivariant_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

df = pd.read_csv('/content/drive/MyDrive/advertising.csv')
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
df.Newspaper.mean()
df.Newspaper.fillna(df.Newspaper.mean(), inplace = True)
df

/tmp/ipykernel_876/411395535.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Newspaper.fillna(df.Newspaper.mean(), inplace = True)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
lr = linear_model.LinearRegression()
lr.fit(df[["TV", "Radio", "Newspaper"]],df.Sales)
lr.predict([[200, 20, 35.2]]) # 17.66773699
lr.coef_ # 0.05444333, 0.1068452 , 0.00064038 represents m1, m2, m3 in the formula
lr.intercept_ # 4.619625400823253 represents b in the formula
# y= m1x1 + m2x2 + m3x3 + b (where y represents predicted_sales)
predicted_sales = 0.05444333*200 + 0.1068452*20 + 0.00064038*35.2 + 4.619625400823253
print (predicted_sales)

17.66773677682325

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(